name: Static Analysis

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - black
          - codespell
          - flake8
          - mypy
    name: ${{ matrix.tox_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python "3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox
        run: python -m pip install tox
      - name: Run tox
        run: python -m tox --skip-missing-interpreters false -e ${{ matrix.tox_env }}
